config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'
  
  get 'jobs', to: 'welcome#jobs'
  root 'welcome#download'
  get 'download', to: 'welcome#download'
  get 'apply-writer', to: 'welcome#apply'
  post 'apply-writer', to: 'welcome#apply_create'
  get 'top', to: 'welcome#top'

  get 'categories/recommend(/:category)', to: 'categories#recommend', as: 'recommend'
  get 'categories/recent', to: 'categories#recent', as: 'recent'
  get 'categories/newest', to: 'categories#newest', as: 'newest'

  resources :categories,only: ["index","show"] do
    resources :novels, only: ["show"]
  end

  resources :novels, only: [] do
    resources :articles, only: ['show']
  end

  resources :authors, only: ["show"]

  get 'search', to: 'novels#search'

end

app/views/shared/_footer.html.haml
%footer#footer
  .container
    .row.hidden-sx
      .col-sm-6
        .app-link
          =link_to (image_tag "en_generic_rgb_wo_45.png"), "https://play.google.com/store/apps/details?id=com.novel.reader"
          =link_to (image_tag "ios.svg"), "https://itunes.apple.com/us/app/xiao-shuo-wang-shou-ji-wang/id909020263"
        .clearfix

    %span.separated
    %span 本站資料來自互聯網, 由會員上載及自行管理. 版權無從考証. 書庫及論壇書籍版權屬於原作者. <br>不得以任何形式用于商業用途。如發現章節或資料錯誤, 版權疑問, 作品內容有違相關法律等情況, 請向我們舉報, 我們將立即刪除.

app/views/shared/_header.html.haml
#header.navbar.navbar-default{:role => "navigation"}
  .container
    .navbar-header
      .masthead-brand
        = link_to root_path , :class => "navbar-brand" do
          = image_tag "app_icon.png"
          %span 小說王
      %nav.navbar-mobile.visible-xs
        %a.js-mobile-btn{:href => "#"}
          %i.fa.fa-bars.fa-fw
    %nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to "下載APP", download_path
        %li.apply-nav
          = link_to "我要投稿", apply_writer_path

app/views/shared/_mobile.html.haml
%section#mobile-wrapper
  %ul.list-group
    %li.list-group-item
      = link_to root_path do 
        %i.fa.fa-home.fa-fw
        首頁
    %li.list-group-item.ind
      = link_to download_path do 
        %i.fa.fa-home.fa-fw
        APP 下載
    %li.list-group-item
      = link_to categories_path do 
        %i.fa.fa-cubes.fa-fw
        小說分類
    %li.list-group-item
      = link_to top_path do 
        %i.fa.fa-trophy.fa-fw
        排行榜
    %li.list-group-item
      = link_to recommend_path do 
        %i.fa.fa-thumbs-up.fa-fw
        推薦小說
    %li.list-group-item
      = link_to apply_writer_path do
        %i.fa.fa-edit.fa-fw
        作者投稿
    %li.list-group-item
      = link_to jobs_path do
        %i.fa.fa-users.fa-fw
        加入我們
    %li.list-group-item.js-close-menu
      %a{:href => "/"} 
        %i.fa.fa-caret-right.fa-fw
        關閉目錄

app/views/shared/_sidebar.html.haml
%section.left-wrapper.full.col-xs-2.hidden-xs
  .left-wrapper-top.text-right.row
    %a#close-sidebar-btn.btn.btn-default.btn-sm.visible-xs(type="button")
      %i.fa.fa-fw.fa-arrow-left
      %span.hidden-sm 收起工具欄
  %ul.list-group
    %li.list-group-item.list-group-title 最新更新
    %li.list-group-item
      = link_to "近期更新", recent_path
    %li.list-group-item
      = link_to '最新上架', newest_path
  %ul.list-group
    %li.list-group-item.list-group-title 小說分類
    %li.list-group-item.active
      = link_to "全部分類", categories_path
    - Category.where('id > 12').each do |category|
      %li.list-group-item
        = link_to category.name, category_path(category)
  %ul.list-group
    %li.list-group-item.list-group-title 推薦熱門小說
    %li.list-group-item.active
      = link_to "全部分類", recommend_path
    - RecommendCategory.all.each do |recommend_category|
      %li.list-group-item
        = link_to recommend_category.name, recommend_path(recommend_category)

app/views/shared/_sidebar_bookview.html.haml
%section.left-wrapper.full.col-xs-2.hidden-xs
  .left-wrapper-top.text-right.row
    %a#close-sidebar-btn.btn.btn-default.btn-sm.visible-xs(type="button")
      %i.fa.fa-fw.fa-arrow-left
      %span.hidden-sm 收起工具欄
  %ul.list-group
    %li.list-group-item.list-group-title 前後十章節
    - novel_articles.each_with_index do |article,i|
      - if article.id == article_id
        - if i >= 9
          - (i-9..i-1).each do |j|
            %li.list-group-item
              = link_to novel_articles[j].subject + " :"+novel_articles[j].title,novel_article_path(novel,novel_articles[j])
        - else
          - (0..i-1).each do |j|
            %li.list-group-item
              = link_to novel_articles[j].subject + " :"+novel_articles[j].title,novel_article_path(novel,novel_articles[j])
        %li.list-group-item.active
          = link_to article.subject + " :"+article.title,novel_article_path(novel,article)
        - if (novel_articles.size - 1 - i) >= 9
          - (i+1..i+9).each do |j|
            %li.list-group-item
              = link_to novel_articles[j].subject + " :"+novel_articles[j].title,novel_article_path(novel,novel_articles[j])
        - else
          - (i+1..novel_articles.size - 1).each do |j|
            %li.list-group-item
              = link_to novel_articles[j].subject + " :"+novel_articles[j].title,novel_article_path(novel,novel_articles[j])