config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'
  
  get 'jobs', to: 'welcome#jobs'
  root 'welcome#download'
  get 'download', to: 'welcome#download'
  get 'apply-writer', to: 'welcome#apply'
  post 'apply-writer', to: 'welcome#apply_create'
  get 'top', to: 'welcome#top'

  get 'categories/recommend(/:category)', to: 'categories#recommend', as: 'recommend'
  get 'categories/recent', to: 'categories#recent', as: 'recent'
  get 'categories/newest', to: 'categories#newest', as: 'newest'

  resources :categories,only: ["index","show"] do
    resources :novels, only: ["show"]
  end

  resources :novels, only: [] do
    resources :articles, only: ['show']
  end

  resources :authors, only: ["show"]

  get 'search', to: 'novels#search'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @recommend_novel = Novel.find(15)
    @newest_novel = Novel.find(19)
    @categories = Category.where(is_popular: true)
    @novels = Novel.order("updated_at desc").page(params[:page]).per_page(12)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def apply
    @writer = Writer.new
  end

  def apply_create
    @writer = Writer.new(writer_params)
    unless @writer.save
      render :apply
    end
  end

  def top
    hot_novels_id = HotShip.all.map{|ship| ship.novel_id}.join(',')
    @hot_novels = Novel.where("id in (#{hot_novels_id})").show.select("id,name,author,pic,category_id,slug").order("updated_at DESC").limit(10)

    this_week_novels_id = ThisWeekHotShip.all.map{|ship| ship.novel_id}.join(',')
    @week_novels = Novel.where("id in (#{this_week_novels_id})").show.select("id,name,author,pic,category_id,slug").order("updated_at DESC").limit(10)

    this_month_novels_id = ThisMonthHotShip.all.map{|ship| ship.novel_id}.join(',')
    @month_novels = Novel.where("id in (#{this_month_novels_id})").show.select("id,name,author,pic,category_id,slug").order("updated_at DESC").limit(10)
  end

  private

  def writer_params
    params.require(:writer).permit(:email, :name, :url, :phone, :remark)
  end

end

app/views/welcome/apply.html.haml
= content_for :head do
  <title>小說王 —— 申請成為小說王作家 | 網路作家 | APP作家 </title>
  <meta name="description" content="小說王需要有更多作家的參與, 讓網路作家們的作品能給更多的讀者看到與分享, 希望作家們能來投稿, 成為小說王的簽約作家">
  <meta name="keywords" content="小說投稿,網路作家,出書,投稿,出版,出版社,作者,作家,小說王">
  <meta property="og:title"  content="小說王 —— 申請成為小說王作家 | 網路作家 | APP作家" />
  <meta property="og:image"  content="#{image_url("app_icon.png")}" />
  <meta property="og:url"  content="#{request.url.split('?').first}" />
  <meta property="og:description" content="小說王致力成為最好用的小說閱讀器APP, 提供 言情,穿越,同人,科幻,武俠,歷史,網遊,偵探 等等小說, APP有下載，收藏, 書籤功能，滿足讀者需求！在Google Play, iTunes APP Store 均可下載" />
  <meta property="og:type" content="website" />

#push-container 
  = render 'shared/header'

  .jumbotron.col-centered.narrow
    %h2.text-primary 申請成為小說王作家
    %p.lead 讓網路作家們的作品能給更多的讀者看到與分享
    %p
      有許多人懷抱著作家的夢，但作品沒有流傳的管道; 小說王希望打造一個平台，誠摯邀請你來成為我們的簽約作家
    %p
      = form_for @writer, url: apply_writer_path,:html => {:class => "form-horizontal", multipart: true} do |f|
        - if @writer.errors.any?
          #error_explanation
            %h3.text-danger 無法寄出訊息，請檢查以下錯誤:
            %ul
              - @writer.errors.full_messages.each do |msg|
                %li.text-danger= msg
        .form-group
          %label.col-sm-2.control-label{:for => "inputEmail3"} Email
          .col-sm-10
            = f.text_field(:email, class: "form-control", :step => 'any')
        .form-group
          %label.col-sm-2.control-label{:for => "inputEmail3"} 姓名(筆名)
          .col-sm-10
            = f.text_field(:name, class: "form-control", :step => 'any')
        .form-group
          %label.col-sm-2.control-label{:for => "inputEmail3"} 作品連結(個人網站)
          .col-sm-10
            = f.text_field(:url, class: "form-control", :step => 'any')
        .form-group
          %label.col-sm-2.control-label{:for => "inputEmail3"} 電話(可不提供)
          .col-sm-10
            = f.text_field(:phone, class: "form-control", :step => 'any')
        .form-group
          %label.col-sm-2.control-label{:for => "inputEmail3"} 備註
          .col-sm-10
            = f.text_area(:remark, class: "form-control", :step => 'any')
        .form-group
          %button.btn.btn-default{:type => "submit"} 寄出

= render 'shared/mobile'

app/views/welcome/apply_create.html.haml
= render 'shared/header'
.jumbotron.col-centered.narrow
  %h2.text-primary 謝謝你，我們會儘快跟你連絡！

app/views/welcome/download.html.haml
= content_for :head do
  <title> 小說王APP下載 | 小說王搜集各類小說 |小說網站</title>
  <meta name="description" content="小說王致力成為最好用的小說閱讀器APP, 提供 言情,穿越,同人,科幻,武俠,歷史,網遊,偵探 等等小說, APP有下載，收藏, 書籤功能，滿足讀者需求！在Google Play, iTunes APP Store 均可下載">
  <meta name="keywords" content="小說王,小说网,言情小说,青春小说,玄幻小说,武侠小说,都市小说,历史小说,网络小说,原创网络文学,完整小說,言情小說,穿越小說,同人小說,科幻小說,武俠小說,歷史小說,網遊小說,偵探小說">
  <meta property="og:title"  content="小說王APP下載 | 小說王搜集各類小說 |小說網站" />
  <meta property="og:image"  content="#{image_url("app-2.png")}" />
  <meta property="og:url"  content="#{request.url.split('?').first}" />
  <meta property="og:description" content="小說王致力成為最好用的小說閱讀器APP, 提供 言情,穿越,同人,科幻,武俠,歷史,網遊,偵探 等等小說, APP有下載，收藏, 書籤功能，滿足讀者需求！在Google Play, iTunes APP Store 均可下載" />
  <meta property="og:type" content="website" />

#push-container 

  = render 'shared/header'

  %section#page

    %section#home-banner
      .container
        .row
          .col-sm-6
            = image_tag "app-2.png", :class => "app-banner hidden-xs img-responsive"
          .col-sm-6
            .slogan
              %h3 小說王 : 最適合你的小說閱讀器
              %p 目前 Android 上最好用的看小說 APP 及小說閱讀器軟體，這款 APP蒐集大量全球的小說，包含：武俠經典，翻譯小說，網路小說，奇幻小說，言情小說等等。
              =link_to (image_tag "en_generic_rgb_wo_45.png"), "https://s3-ap-northeast-1.amazonaws.com/novel-read/app-release.apk"
              =link_to (image_tag "ios.svg"), "https://itunes.apple.com/us/app/xiao-shuo-wang-shou-ji-wang/id909020263"

    %section#home-bar

    %section#wrapper
      .container
        .row.text-center
          .col-sm-4
            .icon-box
              %i.fa.fa-refresh
            %h4 定期更新
            .desc 只要作者有新的文章，小說王每天都會儘快更新文章，期許能滿足愛看小說的大眾。
          .col-sm-4
            .icon-box
              %i.fa.fa-life-ring
            %h4 問題回報
            .desc 小說王的文章多來自作者投稿或是網路搜集, 因為網路來源有多是整理不好或殘缺的小說，我們在APP裡面可以接受讀者的回報，我們會儘快地處理。
          .col-sm-4
            .icon-box
              %i.fa.fa-pencil-square-o
            %h4 作家徵稿
            .desc 熱血的小說家們，擔心作品沒人看見嗎？小說王接受作家的投稿，也會在APP裡面推薦作品，希望有更多好看的小說被讀者們閱讀欣賞。

  = render 'shared/footer'

= render 'shared/mobile'

app/views/welcome/index.html.haml
= content_for :head do
  <title>小說王 —— 手機看小說|手機小說閱讀器|小說APP|手機小說下載|小說應用|小說網站</title>
  <meta name="description" content="小說王致力成為最好用的小說閱讀器APP, 提供 言情,穿越,同人,科幻,武俠,歷史,網遊,偵探 等等小說, APP有下載，收藏, 書籤功能，滿足讀者需求！在Google Play, iTunes APP Store 均可下載">
  <meta name="keywords" content="小說王,小说网,言情小说,青春小说,玄幻小说,武侠小说,都市小说,历史小说,网络小说,原创网络文学,完整小說,言情小說,穿越小說,同人小說,科幻小說,武俠小說,歷史小說,網遊小說,偵探小說">
  <meta property="og:title"  content="小說王 —— 手機看小說|手機小說閱讀器|小說APP|手機小說下載|小說應用|小說網站" />
  <meta property="og:image"  content="#{image_url("app_icon.png")}" />
  <meta property="og:url"  content="#{request.url.split('?').first}" />
  <meta property="og:description" content="小說王致力成為最好用的小說閱讀器APP, 提供 言情,穿越,同人,科幻,武俠,歷史,網遊,偵探 等等小說, APP有下載，收藏, 書籤功能，滿足讀者需求！在Google Play, iTunes APP Store 均可下載" />
  <meta property="og:type" content="website" />

#push-container 

  = render 'shared/header'

  %section#home-wrapper
    .container
      .inner.text-center
        %p 最完整的小說庫, 最好用的閱讀器
        = link_to "閱讀小說", categories_path, class: "btn btn-primary"
        = link_to "成為作家", apply_writer_path, class: "btn btn-success"

  %section#feature-wrapper
    .container
      .row
        .col-md-5
          %h3.title.title_panel 推薦小說
          .row{:itemscope => "", :itemtype => "http://schema.org/Book"}
            .col-sm-4
              .pane_img
                = image_tag @recommend_novel.pic, :class => "img-responsive",:itemprop => "image", alt: @recommend_novel.name
            .col-sm-8
              .pane_detail
                %h4.title.title_book{:itemprop => "name"} #{@recommend_novel.name}
                %p.desc{:itemprop => "description"} #{@recommend_novel.description}
                %br
                = link_to novel_article_path(@recommend_novel,@recommend_novel.articles.first), class: "btn btn-info btn-sm" do
                  馬上閱讀

                = link_to category_novel_path(@recommend_novel.category,@recommend_novel), class: "btn btn-default btn-sm",:itemprop => "url" do
                  詳情
                  %i.fa.fa-long-arrow-right
        .col-md-5
          %h3.title.title_panel 最新小說
          .row{:itemscope => "", :itemtype => "http://schema.org/Book"}
            .col-sm-4
              .pane_img
                = image_tag @newest_novel.pic , :class => "img-responsive",:itemprop => "image",alt: @newest_novel.name
            .col-sm-8
              .pane_detail
                %h4.title.title_book{:itemprop => "name"} #{@newest_novel.name}
                %p.desc{:itemprop => "description"} #{@newest_novel.description}
                %br
                = link_to novel_article_path(@newest_novel,@newest_novel.articles.first), class: "btn btn-info btn-sm" do
                  馬上閱讀
                = link_to category_novel_path(@newest_novel.category,@newest_novel), class: "btn btn-default btn-sm",:itemprop => "url" do
                  詳情
                  %i.fa.fa-long-arrow-right


  %section#page
    .container
      .nav-background
        %ul.nav.nav-pills
          %li.active
            %a{:href => "/"} 全部分類
          - @categories.each do |category|
            %li
              = link_to category.name,category_path(category)
      .box_wrapper
        = render @novels
          
    #with-button
      = will_paginate @novels

    - if @novels.next_page
      .center-div
        #load-more-btn.btn.btn-primary.btn-lg.load-more 更多小說

  = render 'shared/footer'

= render 'shared/mobile'

app/views/welcome/index.js.erb
$container = $('.box_wrapper');
$container.append('<%= j render @novels %>').masonry( 'reloadItems' );

reload_masonry = function() {
  $container.imagesLoaded(function() {
    $container.masonry({
      itemSelector: ".box_item"
    });
  });
};


window.setTimeout(reload_masonry, 100);

<% if @novels.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @novels %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/welcome/jobs.html.haml
= content_for :head do
  <title>申請成為小說王作家 | 小說王網路作家 | APP作家 </title>
  <meta name="description" content="小說王需要有更多作家的參與, 讓網路作家們的作品能給更多的讀者看到與分享, 希望作家們能來投稿, 成為小說王的簽約作家">
  <meta name="keywords" content="小說投稿,網路作家,出書,投稿,出版,出版社,作者,作家,小說王">

#push-container 
  = render 'shared/header'

  .jumbotron
    %h2.text-primary 小說王徵才
    %p.lead 1.Android 工程師
    %p
      %h4.text-info 工作內容
      %h5
        開發小說王Android APP
      %h4.text-info 應徵條件
      %ul
        %li 熟悉 Android
        %li Git
        %li 開發過至少一款 Android APP
      %h4.text-info 加分條件
      %ul
        %li 喜愛閱讀網路小說
        %li Scrum
        %li 寫過 Andriod Test
      %h4.text-info 待遇
      .text-danger NT$ 35000 ~ 80000
      %h4.text-info 如何應徵
      請寄覆歷至:
      = mail_to "stevenko@kosbrother.com"

= render 'shared/mobile'

app/views/welcome/top.html.haml
= content_for :head do
  <title>小說排行榜 | 小說王 —— 手機看小說|手機小說閱讀器|小說APP|手機小說下載|小說應用|小說網站 </title>
  <meta name="description" content="小說排行榜">
  <meta name="keywords" content="熱門小說,本月推薦,本週排行">

#push-container 

  = render 'shared/header'

  %section#page.dark-bg
    .container
      = render 'shared/sidebar'
      %section.right-wrapper.full.col-xs-12.col-sm-10
        %ol.breadcrumb.row.full
          %li
            %a{:href => "/"} 首頁
          %li
            = link_to "小說排行", top_path
        .content
          .row
            .col-md-4
              %h2.title.title_book 熱門小說
              %ul.list-group
                = render partial: 'novels/novel_for_top', collection: @hot_novels, as: :novel

            .col-md-4
              %h2.title.title_book 本月推薦
              %ul.list-group
                = render partial: 'novels/novel_for_top', collection: @week_novels, as: :novel

            .col-md-4
              %h2.title.title_book 本週排行
              %ul.list-group
                = render partial: 'novels/novel_for_top', collection: @month_novels, as: :novel

  = render 'shared/footer'

= render 'shared/mobile'