config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'
  
  get 'jobs', to: 'welcome#jobs'
  root 'welcome#download'
  get 'download', to: 'welcome#download'
  get 'apply-writer', to: 'welcome#apply'
  post 'apply-writer', to: 'welcome#apply_create'
  get 'top', to: 'welcome#top'

  get 'categories/recommend(/:category)', to: 'categories#recommend', as: 'recommend'
  get 'categories/recent', to: 'categories#recent', as: 'recent'
  get 'categories/newest', to: 'categories#newest', as: 'newest'

  resources :categories,only: ["index","show"] do
    resources :novels, only: ["show"]
  end

  resources :novels, only: [] do
    resources :articles, only: ['show']
  end

  resources :authors, only: ["show"]

  get 'search', to: 'novels#search'

end

app/models/novel.rb
class Novel < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end

  def slug_candidates
    [
      :name,
      [:name, :author],
    ]
  end

  belongs_to :category
  has_many :articles

  scope :show, -> {where(:is_show => true)}
  def recrawl_articles_text
    Article.where("novel_id = #{id} and is_show = true").select("id").find_in_batches(:batch_size => 100) do |articles|
      articles.each do |article|
        texts = ArticleText.select("id").where("article_id = #{article.id}")
        ArticleWorker.perform_async(article.id) unless texts.present?
      end 
    end
  end


  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id, type: 'integer'
    indexes :author, :analyzer => "cjk"
    indexes :name, :analyzer => "cjk"
  end

  def self.search(params)
    tire.search(page: params[:page], per_page: 5, load: true) do
      query { string params[:keyword], default_operator: "AND" }
    end
  end

end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def show
    @novel = Novel.friendly.find(params[:id])
    @category = @novel.category
    novel_articles = @novel.articles
    @articles = novel_articles.each_slice(novel_articles.size/3+1).to_a
  end

  def index
  end

  def search
    params[:page] ||= 1
    @novels = Novel.search(params)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/novels/_novel.html.haml
.box_item{:itemscope => "", :itemtype => "http://schema.org/Book"}
  .box_img
    = link_to (image_tag novel.pic, :class => "img-responsive", :itemprop => "image", alt: novel.name), category_novel_path(novel.category,novel),:itemprop => "url"
  .box_detail
    %h5.title
      = link_to category_novel_path(novel.category,novel) do
        %span{:itemprop => "name"} #{novel.name}
    %h6.author{:itemprop => "author"} #{novel.author}

app/views/novels/_novel_for_top.html.haml
%li.list-group-item.media-item
  = link_to "",category_novel_path(novel.category,novel), class: "media-link"
  %span.number #{novel_counter + 1}
  .media-small
    = image_tag novel.pic, :class => "img-responsive"
    %i.fa.fa-fw.fa-book
  .box_detail
    %h5.title
      = link_to novel.name, category_novel_path(novel.category,novel)
    %h6.author #{novel.author}

app/views/novels/search.html.haml
= content_for :head do
  <title>小說搜索 | 小說王搜集各類小說 |小說網站 </title>
  <meta name="description" content="利用小說王搜索網路上各類小說,言情,輕小說,穿越,網路作家">
  <meta name="keywords" content="九把刀,總裁,古靈,重生,典心,刀劍神域,張廉,席絹,三國,金庸,護玄,黑潔明">
  <meta property="og:title"  content="小說搜索 | 小說王搜集各類小說 |小說網站" />
  <meta property="og:image"  content="#{image_url("app_icon.png")}" />
  <meta property="og:url"  content="#{request.url}" />
  <meta property="og:type" content="website" />

#push-container 

  = render 'shared/header'

  %section#page.dark-bg
    .container
      = render 'shared/sidebar'
      %section.right-wrapper.full.col-xs-12.col-sm-10
        %ol.breadcrumb.row.full
          %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
            = link_to root_path,:itemprop => "url" do
              %span{:itemprop => "title"} 首頁
          %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
            %span{:itemprop => "title"} 搜尋
            
        .content
          .content-body
            .box_wrapper
              = render @novels

        #infinite-scrolling.center-div
          = will_paginate @novels

  = render 'partial/footer'

= render 'partial/mobile'

app/views/novels/search.js.erb
$container = $('.content-body .row');
$container.masonry({
  itemSelector: '#marsony-item'
});
$container.append('<%= j render @novels %>').masonry( 'reloadItems' );
$container = $('.content-body .row');
$container.masonry({
  itemSelector: '#marsony-item'
});

<% if @novels.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @novels %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/novels/show.html.haml
= content_for :head do
  <title>#{@novel.name} -- #{@category.name} | 小說王搜集各類小說 |小說網站 </title>
  <meta name="description" content="#{@novel.description}">
  <meta name="keywords" content="#{@novel.name},#{@category.name},#{@novel.author}">
  <meta property="og:title"  content="#{@novel.name}-- #{@category.name} | 小說王搜集各類小說 |小說網站" />
  <meta property="og:image"  content="#{image_url(@novel.pic)}" />
  <meta property="og:url"  content="#{request.url.split('?').first}" />
  <meta property="og:description" content="#{@novel.description}" />
  <meta property="og:type" content="book">
  <meta property="book:author" content="#{@novel.author}">
  <meta property="book:tag" content="#{@category.name}">

#push-container 

  = render 'shared/header'

  %section#page.dark-bg
    .container
      = render 'shared/sidebar'
      %section.right-wrapper.full.col-xs-12.col-sm-10
        %ol.breadcrumb.row.full
          %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
            = link_to root_path,:itemprop => "url" do
              %span{:itemprop => "title"} 首頁
          %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
            = link_to category_path(@category),:itemprop => "url" do
              %span{:itemprop => "title"} #{@category.name}
          %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
            = link_to category_novel_path(@category,@novel),:itemprop => "url" do
              %span{:itemprop => "title"} #{@novel.name}
              
        .content{:itemscope => "", :itemtype => "http://schema.org/Book"}
          .row.pane
            .col-sm-4
              .pane_img
                = image_tag @novel.pic , :class => "img-responsive",:itemprop => "image", alt: @novel.name
            .col-sm-8
              .pane_detail
                %h4.title.title_book{:itemprop => "name"} #{@novel.name}
                %p{:itemprop => "description"} #{@novel.description}
                %hr
                = link_to author_path(@novel.author), class: "btn btn-default btn-sm",:itemprop => "author" do
                  %i.fa.fa-user.fa-fw 
                  #{@novel.author}

                = link_to novel_article_path(@novel,@articles[0].first), class: "btn btn-default btn-sm" do
                  %i.fa.fa-plus.fa-fw 
                  點擊閱讀

          .content-body
            %hr
            .row
              .col-md-4
                %ul.list-group.panel
                  - @articles[0].each do |article|
                    %li.list-group-item
                      = link_to article.subject + " :"+article.title, novel_article_path(@novel,article)
              .col-md-4
                %ul.list-group.panel
                  - @articles[1].each do |article|
                    %li.list-group-item
                      = link_to article.subject + " :"+article.title, novel_article_path(@novel,article)

              .col-md-4
                %ul.list-group.panel
                  - @articles[2].each do |article|
                    %li.list-group-item
                      = link_to article.subject + " :"+article.title, novel_article_path(@novel,article)

  = render 'shared/footer'

= render 'shared/mobile'